version: "2"

services:
  redis:
    image: redis:latest
  web:
    build: .
    image: multicast
    command: daphne -b 0.0.0.0 -p 9000 multichat.asgi:application 
    volumes:
      - .:/code
    links:
      - redis
    deploy:
      mode: replicated
      replicas: 5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dj
      MYSQL_USER: dj
      MYSQL_PASSWORD: sj
      MYSQL_HOST: db
  migrate:
    image: multicast
    depends_on: 
      - web 
      - db
    command: python manage.py migrate 
    volumes:
      - .:/code
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dj
      MYSQL_USER: dj
      MYSQL_PASSWORD: sj
      MYSQL_HOST: db
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dj
      MYSQL_USER: dj
      MYSQL_PASSWORD: sj
  webserver:
    depends_on:
      - web
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data: {}
